HEADER_LENGTH = 0x1c

ARPHRD_NETROM = 0
ARPHRD_ETHER = 1
ARPHRD_EETHER = 2
ARPHRD_AX25 = 3
ARPHRD_PRONET = 4
ARPHRD_CHAOS = 5
ARPHRD_IEEE802 = 6
ARPHRD_ARCNET = 7
ARPHRD_APPLETLK = 8
ARPHRD_LANSTAR = 9
ARPHRD_FRELAY = 15
ARPHRD_DLCI = ARPHRD_FRELAY
ARPHRD_ATM = 19
ARPHRD_METRICOM = 23
ARPHRD_IPSEC = 31

ARPOP_REQUEST = 1
ARPOP_REPLY = 2
ARPOP_REVREQUEST = 3
ARPOP_REVREPLY = 4
ARPOP_INVREQUEST = 8
ARPOP_INVREPLY = 9

