class Enum:  # Boost.Python.enum
    # Will be filled with constants of child classes
    # Note that the definition differs from
    # the Boost variant. Here, the values would be integer,
    # but not of childclass type.
    values = {}

    def __init__(self):
        d = self.__class__.__dict__
        for t in d:
            if not t[0] == "_":
                self.values[t] = d[t]

class GameStateTypes(Enum):
    GAMESTATE_ON = -1
    GAMESTATE_OVER = -1
    GAMESTATE_EXTENDED = -1

class PopupStates(Enum):
    POPUPSTATE_IMMEDIATE = -1
    POPUPSTATE_QUEUED = -1
    POPUPSTATE_MINIMIZED = -1

class CameraLookAtTypes(Enum):
    CAMERALOOKAT_NORMAL = -1
    CAMERALOOKAT_CITY_ZOOM_IN = -1
    CAMERALOOKAT_BATTLE = -1
    CAMERALOOKAT_BATTLE_ZOOM_IN = -1
    CAMERALOOKAT_IMMEDIATE = -1

class CameraMovementSpeeds(Enum):
    CAMERAMOVEMENTSPEED_NORMAL = -1
    CAMERAMOVEMENTSPEED_SLOW = -1
    CAMERAMOVEMENTSPEED_FAST = -1

class ZoomLevelTypes(Enum):
    ZOOM_UNKNOWN = -1
    ZOOM_GLOBEVIEW = -1
    ZOOM_NORMAL = -1
    ZOOM_DETAIL = -1

class DirectionTypes(Enum):
    NO_DIRECTION = -1
    DIRECTION_NORTH = -1
    DIRECTION_NORTHEAST = -1
    DIRECTION_EAST = -1
    DIRECTION_SOUTHEAST = -1
    DIRECTION_SOUTH = -1
    DIRECTION_SOUTHWEST = -1
    DIRECTION_WEST = -1
    DIRECTION_NORTHWEST = -1
    NUM_DIRECTION_TYPES = -1

class CardinalDirectionTypes(Enum):
    NO_CARDINALDIRECTION = -1
    CARDINALDIRECTION_NORTH = -1
    CARDINALDIRECTION_EAST = -1
    CARDINALDIRECTION_SOUTH = -1
    CARDINALDIRECTION_WEST = -1
    NUM_CARDINALDIRECTION_TYPES = -1

class ColorTypes(Enum):
    NO_COLOR = -1

class PlayerColorTypes(Enum):
    NO_PLAYERCOLOR = -1

class PlotStyles(Enum):
    PLOT_STYLE_NONE = -1
    PLOT_STYLE_NUMPAD_1 = -1
    PLOT_STYLE_NUMPAD_2 = -1
    PLOT_STYLE_NUMPAD_3 = -1
    PLOT_STYLE_NUMPAD_4 = -1
    PLOT_STYLE_NUMPAD_6 = -1
    PLOT_STYLE_NUMPAD_7 = -1
    PLOT_STYLE_NUMPAD_8 = -1
    PLOT_STYLE_NUMPAD_9 = -1
    PLOT_STYLE_NUMPAD_1_ANGLED = -1
    PLOT_STYLE_NUMPAD_2_ANGLED = -1
    PLOT_STYLE_NUMPAD_3_ANGLED = -1
    PLOT_STYLE_NUMPAD_4_ANGLED = -1
    PLOT_STYLE_NUMPAD_6_ANGLED = -1
    PLOT_STYLE_NUMPAD_7_ANGLED = -1
    PLOT_STYLE_NUMPAD_8_ANGLED = -1
    PLOT_STYLE_NUMPAD_9_ANGLED = -1
    PLOT_STYLE_BOX_FILL = -1
    PLOT_STYLE_BOX_OUTLINE = -1
    PLOT_STYLE_RIVER_SOUTH = -1
    PLOT_STYLE_RIVER_EAST = -1
    PLOT_STYLE_SIDE_ARROWS = -1
    PLOT_STYLE_CIRCLE = -1
    PLOT_STYLE_TARGET = -1
    PLOT_STYLE_DOT_TARGET = -1
    PLOT_STYLE_WAVES = -1
    PLOT_STYLE_DOTS = -1
    PLOT_STYLE_CIRCLES = -1

class PlotLandscapeLayers(Enum):
    PLOT_LANDSCAPE_LAYER_ALL = -1
    PLOT_LANDSCAPE_LAYER_BASE = -1
    PLOT_LANDSCAPE_LAYER_RECOMMENDED_PLOTS = -1
    PLOT_LANDSCAPE_LAYER_WORLD_BUILDER = -1
    PLOT_LANDSCAPE_LAYER_NUMPAD_HELP = -1
    PLOT_LANDSCAPE_LAYER_REVEALED_PLOTS = -1

class AreaBorderLayers(Enum):
    AREA_BORDER_LAYER_REVEALED_PLOTS = -1
    AREA_BORDER_LAYER_WORLD_BUILDER = -1
    AREA_BORDER_LAYER_FOUNDING_BORDER = -1
    AREA_BORDER_LAYER_CITY_RADIUS = -1
    AREA_BORDER_LAYER_RANGED = -1
    AREA_BORDER_LAYER_HIGHLIGHT_PLOT = -1
    AREA_BORDER_LAYER_BLOCKADING = -1
    AREA_BORDER_LAYER_BLOCKADED = -1
    NUM_AREA_BORDER_LAYERS = -1

class InterfaceModeTypes(Enum):
    NO_INTERFACEMODE = -1
    INTERFACEMODE_SELECTION = -1
    INTERFACEMODE_PING = -1
    INTERFACEMODE_SIGN = -1
    INTERFACEMODE_GRIP = -1
    INTERFACEMODE_GLOBELAYER_INPUT = -1
    INTERFACEMODE_GO_TO = -1
    INTERFACEMODE_GO_TO_TYPE = -1
    INTERFACEMODE_GO_TO_ALL = -1
    INTERFACEMODE_ROUTE_TO = -1
    INTERFACEMODE_AIRLIFT = -1
    INTERFACEMODE_NUKE = -1
    INTERFACEMODE_RECON = -1
    INTERFACEMODE_PARADROP = -1
    INTERFACEMODE_AIRBOMB = -1
    INTERFACEMODE_RANGE_ATTACK = -1
    INTERFACEMODE_AIRSTRIKE = -1
    INTERFACEMODE_REBASE = -1
    INTERFACEMODE_PYTHON_PICK_PLOT = -1
    INTERFACEMODE_SAVE_PLOT_NIFS = -1
    NUM_INTERFACEMODE_TYPES = -1

class InterfaceMessageTypes(Enum):
    NO_MESSAGE_TYPE = -1
    MESSAGE_TYPE_INFO = -1
    MESSAGE_TYPE_DISPLAY_ONLY = -1
    MESSAGE_TYPE_MAJOR_EVENT = -1
    MESSAGE_TYPE_MINOR_EVENT = -1
    MESSAGE_TYPE_CHAT = -1
    MESSAGE_TYPE_COMBAT_MESSAGE = -1
    MESSAGE_TYPE_QUEST = -1
    NUM_INTERFACE_MESSAGE_TYPES = -1

class MinimapModeTypes(Enum):
    NO_MINIMAPMODE = -1
    MINIMAPMODE_TERRITORY = -1
    MINIMAPMODE_TERRAIN = -1
    MINIMAPMODE_REPLAY = -1
    MINIMAPMODE_MILITARY = -1
    NUM_MINIMAPMODE_TYPES = -1

class EngineDirtyBits(Enum):
    GlobeTexture_DIRTY_BIT = -1
    MinimapTexture_DIRTY_BIT = -1
    CultureBorders_DIRTY_BIT = -1
    NUM_ENGINE_DIRTY_BITS = -1

class InterfaceDirtyBits(Enum):
    SelectionCamera_DIRTY_BIT = -1
    Fog_DIRTY_BIT = -1
    GlobeLayer_DIRTY_BIT = -1
    GlobeInfo_DIRTY_BIT = -1
    Waypoints_DIRTY_BIT = -1
    PercentButtons_DIRTY_BIT = -1
    MiscButtons_DIRTY_BIT = -1
    PlotListButtons_DIRTY_BIT = -1
    SelectionButtons_DIRTY_BIT = -1
    CitizenButtons_DIRTY_BIT = -1
    ResearchButtons_DIRTY_BIT = -1
    Event_DIRTY_BIT = -1
    Center_DIRTY_BIT = -1
    GameData_DIRTY_BIT = -1
    Score_DIRTY_BIT = -1
    TurnTimer_DIRTY_BIT = -1
    Help_DIRTY_BIT = -1
    MinimapSection_DIRTY_BIT = -1
    SelectionSound_DIRTY_BIT = -1
    Cursor_DIRTY_BIT = -1
    CityInfo_DIRTY_BIT = -1
    UnitInfo_DIRTY_BIT = -1
    Popup_DIRTY_BIT = -1
    CityScreen_DIRTY_BIT = -1
    InfoPane_DIRTY_BIT = -1
    Flag_DIRTY_BIT = -1
    HighlightPlot_DIRTY_BIT = -1
    ColoredPlots_DIRTY_BIT = -1
    BlockadedPlots_DIRTY_BIT = -1
    Financial_Screen_DIRTY_BIT = -1
    Foreign_Screen_DIRTY_BIT = -1
    Soundtrack_DIRTY_BIT = -1
    Domestic_Advisor_DIRTY_BIT = -1
    Espionage_Advisor_DIRTY_BIT = -1
    Advanced_Start_DIRTY_BIT = -1
    NUM_INTERFACE_DIRTY_BITS = -1

class CityTabTypes(Enum):
    CITYTAB_UNITS = -1
    CITYTAB_BUILDINGS = -1
    CITYTAB_WONDERS = -1
    NUM_CITYTAB_TYPES = -1

class WidgetTypes(Enum):
    WIDGET_PLOT_LIST = -1
    WIDGET_PLOT_LIST_SHIFT = -1
    WIDGET_CITY_SCROLL = -1
    WIDGET_LIBERATE_CITY = -1
    WIDGET_CITY_NAME = -1
    WIDGET_UNIT_NAME = -1
    WIDGET_CREATE_GROUP = -1
    WIDGET_DELETE_GROUP = -1
    WIDGET_TRAIN = -1
    WIDGET_CONSTRUCT = -1
    WIDGET_CREATE = -1
    WIDGET_MAINTAIN = -1
    WIDGET_HURRY = -1
    WIDGET_MENU_ICON = -1
    WIDGET_CONSCRIPT = -1
    WIDGET_ACTION = -1
    WIDGET_DISABLED_CITIZEN = -1
    WIDGET_CITIZEN = -1
    WIDGET_FREE_CITIZEN = -1
    WIDGET_ANGRY_CITIZEN = -1
    WIDGET_CHANGE_SPECIALIST = -1
    WIDGET_RESEARCH = -1
    WIDGET_TECH_TREE = -1
    WIDGET_CHANGE_PERCENT = -1
    WIDGET_CITY_TAB = -1
    WIDGET_CONTACT_CIV = -1
    WIDGET_SCORE_BREAKDOWN = -1
    WIDGET_ZOOM_CITY = -1
    WIDGET_END_TURN = -1
    WIDGET_LAUNCH_VICTORY = -1
    WIDGET_CONVERT = -1
    WIDGET_WB_SAVE_BUTTON = -1
    WIDGET_WB_LOAD_BUTTON = -1
    WIDGET_WB_ALL_PLOTS_BUTTON = -1
    WIDGET_WB_LANDMARK_BUTTON = -1
    WIDGET_WB_ERASE_BUTTON = -1
    WIDGET_WB_EXIT_BUTTON = -1
    WIDGET_WB_UNIT_EDIT_BUTTON = -1
    WIDGET_WB_CITY_EDIT_BUTTON = -1
    WIDGET_WB_NORMAL_PLAYER_TAB_MODE_BUTTON = -1
    WIDGET_WB_NORMAL_MAP_TAB_MODE_BUTTON = -1
    WIDGET_WB_REVEAL_TAB_MODE_BUTTON = -1
    WIDGET_WB_DIPLOMACY_MODE_BUTTON = -1
    WIDGET_WB_REVEAL_ALL_BUTTON = -1
    WIDGET_WB_UNREVEAL_ALL_BUTTON = -1
    WIDGET_WB_REGENERATE_MAP = -1
    WIDGET_AUTOMATE_CITIZENS = -1
    WIDGET_AUTOMATE_PRODUCTION = -1
    WIDGET_EMPHASIZE = -1
    WIDGET_DIPLOMACY_RESPONSE = -1
    WIDGET_GENERAL = -1
    WIDGET_FILE_LISTBOX = -1
    WIDGET_FILE_EDITBOX = -1
    WIDGET_TRADE_ITEM = -1
    WIDGET_UNIT_MODEL = -1
    WIDGET_FLAG = -1
    WIDGET_POPUP_QUEUE = -1
    WIDGET_PYTHON = -1
    WIDGET_HELP_MAINTENANCE = -1
    WIDGET_HELP_RELIGION = -1
    WIDGET_HELP_RELIGION_CITY = -1
    WIDGET_HELP_CORPORATION_CITY = -1
    WIDGET_HELP_NATIONALITY = -1
    WIDGET_HELP_DEFENSE = -1
    WIDGET_HELP_HEALTH = -1
    WIDGET_HELP_HAPPINESS = -1
    WIDGET_HELP_POPULATION = -1
    WIDGET_HELP_PRODUCTION = -1
    WIDGET_HELP_CULTURE = -1
    WIDGET_HELP_GREAT_PEOPLE = -1
    WIDGET_HELP_GREAT_GENERAL = -1
    WIDGET_HELP_SELECTED = -1
    WIDGET_HELP_BUILDING = -1
    WIDGET_HELP_TRADE_ROUTE_CITY = -1
    WIDGET_HELP_ESPIONAGE_COST = -1
    WIDGET_HELP_TECH_ENTRY = -1
    WIDGET_HELP_TECH_PREPREQ = -1
    WIDGET_HELP_OBSOLETE = -1
    WIDGET_HELP_OBSOLETE_BONUS = -1
    WIDGET_HELP_OBSOLETE_SPECIAL = -1
    WIDGET_HELP_MOVE_BONUS = -1
    WIDGET_HELP_FREE_UNIT = -1
    WIDGET_HELP_FEATURE_PRODUCTION = -1
    WIDGET_HELP_WORKER_RATE = -1
    WIDGET_HELP_TRADE_ROUTES = -1
    WIDGET_HELP_HEALTH_RATE = -1
    WIDGET_HELP_HAPPINESS_RATE = -1
    WIDGET_HELP_FREE_TECH = -1
    WIDGET_HELP_LOS_BONUS = -1
    WIDGET_HELP_MAP_CENTER = -1
    WIDGET_HELP_MAP_REVEAL = -1
    WIDGET_HELP_MAP_TRADE = -1
    WIDGET_HELP_TECH_TRADE = -1
    WIDGET_HELP_GOLD_TRADE = -1
    WIDGET_HELP_OPEN_BORDERS = -1
    WIDGET_HELP_DEFENSIVE_PACT = -1
    WIDGET_HELP_PERMANENT_ALLIANCE = -1
    WIDGET_HELP_VASSAL_STATE = -1
    WIDGET_HELP_BUILD_BRIDGE = -1
    WIDGET_HELP_IRRIGATION = -1
    WIDGET_HELP_IGNORE_IRRIGATION = -1
    WIDGET_HELP_WATER_WORK = -1
    WIDGET_HELP_IMPROVEMENT = -1
    WIDGET_HELP_DOMAIN_EXTRA_MOVES = -1
    WIDGET_HELP_ADJUST = -1
    WIDGET_HELP_TERRAIN_TRADE = -1
    WIDGET_HELP_SPECIAL_BUILDING = -1
    WIDGET_HELP_YIELD_CHANGE = -1
    WIDGET_HELP_BONUS_REVEAL = -1
    WIDGET_HELP_CIVIC_REVEAL = -1
    WIDGET_HELP_PROCESS_INFO = -1
    WIDGET_HELP_FOUND_RELIGION = -1
    WIDGET_HELP_FOUND_CORPORATION = -1
    WIDGET_HELP_FINANCE_NUM_UNITS = -1
    WIDGET_HELP_FINANCE_UNIT_COST = -1
    WIDGET_HELP_FINANCE_AWAY_SUPPLY = -1
    WIDGET_HELP_FINANCE_CITY_MAINT = -1
    WIDGET_HELP_FINANCE_CIVIC_UPKEEP = -1
    WIDGET_HELP_FINANCE_FOREIGN_INCOME = -1
    WIDGET_HELP_FINANCE_INFLATED_COSTS = -1
    WIDGET_HELP_FINANCE_GROSS_INCOME = -1
    WIDGET_HELP_FINANCE_NET_GOLD = -1
    WIDGET_HELP_FINANCE_GOLD_RESERVE = -1
    WIDGET_HELP_PROMOTION = -1
    WIDGET_CHOOSE_EVENT = -1
    WIDGET_PEDIA_JUMP_TO_TECH = -1
    WIDGET_PEDIA_JUMP_TO_UNIT = -1
    WIDGET_PEDIA_JUMP_TO_BUILDING = -1
    WIDGET_PEDIA_JUMP_TO_DERIVED_TECH = -1
    WIDGET_PEDIA_JUMP_TO_REQUIRED_TECH = -1
    WIDGET_PEDIA_BACK = -1
    WIDGET_PEDIA_FORWARD = -1
    WIDGET_PEDIA_JUMP_TO_BONUS = -1
    WIDGET_PEDIA_MAIN = -1
    WIDGET_PEDIA_JUMP_TO_PROMOTION = -1
    WIDGET_PEDIA_JUMP_TO_UNIT_COMBAT = -1
    WIDGET_PEDIA_JUMP_TO_IMPROVEMENT = -1
    WIDGET_PEDIA_JUMP_TO_CIVIC = -1
    WIDGET_PEDIA_JUMP_TO_CIV = -1
    WIDGET_PEDIA_JUMP_TO_LEADER = -1
    WIDGET_PEDIA_JUMP_TO_SPECIALIST = -1
    WIDGET_PEDIA_JUMP_TO_PROJECT = -1
    WIDGET_PEDIA_JUMP_TO_TERRAIN = -1
    WIDGET_PEDIA_JUMP_TO_FEATURE = -1
    WIDGET_TURN_EVENT = -1
    WIDGET_FOREIGN_ADVISOR = -1
    WIDGET_REVOLUTION = -1
    WIDGET_PEDIA_DESCRIPTION = -1
    WIDGET_PEDIA_DESCRIPTION_NO_HELP = -1
    WIDGET_DEAL_KILL = -1
    WIDGET_MINIMAP_HIGHLIGHT = -1
    WIDGET_PRODUCTION_MOD_HELP = -1
    WIDGET_LEADERHEAD = -1
    WIDGET_LEADER_LINE = -1
    WIDGET_COMMERCE_MOD_HELP = -1
    WIDGET_CLOSE_SCREEN = -1
    WIDGET_PEDIA_JUMP_TO_RELIGION = -1
    WIDGET_PEDIA_JUMP_TO_CORPORATION = -1
    WIDGET_GLOBELAYER = -1
    WIDGET_GLOBELAYER_OPTION = -1
    WIDGET_GLOBELAYER_TOGGLE = -1

    NUM_WIDGET_TYPES = -1

class ButtonPopupTypes(Enum):
    BUTTONPOPUP_TEXT = -1
    BUTTONPOPUP_MAIN_MENU = -1
    BUTTONPOPUP_CONFIRM_MENU = -1
    BUTTONPOPUP_DECLAREWARMOVE = -1
    BUTTONPOPUP_CONFIRMCOMMAND = -1
    BUTTONPOPUP_LOADUNIT = -1
    BUTTONPOPUP_LEADUNIT = -1
    BUTTONPOPUP_DOESPIONAGE = -1
    BUTTONPOPUP_DOESPIONAGE_TARGET = -1
    BUTTONPOPUP_CHOOSETECH = -1
    BUTTONPOPUP_RAZECITY = -1
    BUTTONPOPUP_DISBANDCITY = -1
    BUTTONPOPUP_CHOOSEPRODUCTION = -1
    BUTTONPOPUP_CHANGECIVIC = -1
    BUTTONPOPUP_CHANGERELIGION = -1
    BUTTONPOPUP_CHOOSEELECTION = -1
    BUTTONPOPUP_DIPLOVOTE = -1
    BUTTONPOPUP_ALARM = -1
    BUTTONPOPUP_DEAL_CANCELED = -1
    BUTTONPOPUP_PYTHON = -1
    BUTTONPOPUP_PYTHON_SCREEN = -1
    BUTTONPOPUP_DETAILS = -1
    BUTTONPOPUP_ADMIN = -1
    BUTTONPOPUP_ADMIN_PASSWORD = -1
    BUTTONPOPUP_EXTENDED_GAME = -1
    BUTTONPOPUP_DIPLOMACY = -1
    BUTTONPOPUP_ADDBUDDY = -1
    BUTTONPOPUP_FORCED_DISCONNECT = -1
    BUTTONPOPUP_PITBOSS_DISCONNECT = -1
    BUTTONPOPUP_KICKED = -1
    BUTTONPOPUP_VASSAL_DEMAND_TRIBUTE = -1
    BUTTONPOPUP_VASSAL_GRANT_TRIBUTE = -1
    BUTTONPOPUP_EVENT = -1
    BUTTONPOPUP_FREE_COLONY = -1
    BUTTONPOPUP_LAUNCH = -1
    BUTTONPOPUP_FOUND_RELIGION = -1
    BUTTONPOPUP_CONFIRM_MENU_KI = -1

    NUM_BUTTONPOPUP_TYPES = -1

class ClimateTypes(Enum):
    NO_CLIMATE = -1

class SeaLevelTypes(Enum):
    NO_SEALEVEL = -1

class CustomMapOptionTypes(Enum):
    NO_CUSTOM_MAPOPTION = -1

class WorldSizeTypes(Enum):
    NO_WORLDSIZE = -1
    WORLDSIZE_DUEL = -1
    WORLDSIZE_TINY = -1
    WORLDSIZE_SMALL = -1
    WORLDSIZE_STANDARD = -1
    WORLDSIZE_LARGE = -1
    WORLDSIZE_HUGE = -1
    NUM_WORLDSIZE_TYPES = -1

class TerrainTypes(Enum):
    NO_TERRAIN = -1

class PlotTypes(Enum):
    NO_PLOT = -1
    PLOT_PEAK = -1
    PLOT_HILLS = -1
    PLOT_LAND = -1
    PLOT_OCEAN = -1
    NUM_PLOT_TYPES = -1

class YieldTypes(Enum):
    NO_YIELD = -1
    YIELD_FOOD = -1
    YIELD_PRODUCTION = -1
    YIELD_COMMERCE = -1
    NUM_YIELD_TYPES = -1

class CommerceTypes(Enum):
    COMMERCE_GOLD = -1
    COMMERCE_RESEARCH = -1
    COMMERCE_CULTURE = -1
    COMMERCE_ESPIONAGE = -1
    NUM_COMMERCE_TYPES = -1

class AdvisorTypes(Enum):
    NO_ADVISOR = -1

class FlavorTypes(Enum):
    NO_FLAVOR = -1

class EmphasizeTypes(Enum):
    NO_EMPHASIZE = -1

class GameOptionTypes(Enum):
    NO_GAMEOPTION = -1
    GAMEOPTION_ADVANCED_START = -1
    GAMEOPTION_NO_CITY_RAZING = -1
    GAMEOPTION_NO_CITY_FLIPPING = -1
    GAMEOPTION_FLIPPING_AFTER_CONQUEST = -1
    GAMEOPTION_NO_BARBARIANS = -1
    GAMEOPTION_RAGING_BARBARIANS = -1
    GAMEOPTION_AGGRESSIVE_AI = -1
    GAMEOPTION_LEAD_ANY_CIV = -1
    GAMEOPTION_RANDOM_PERSONALITIES = -1
    GAMEOPTION_PICK_RELIGION = -1
    GAMEOPTION_NO_TECH_TRADING = -1
    GAMEOPTION_NO_TECH_BROKERING = -1
    GAMEOPTION_PERMANENT_ALLIANCES = -1
    GAMEOPTION_ALWAYS_WAR = -1
    GAMEOPTION_ALWAYS_PEACE = -1
    GAMEOPTION_ONE_CITY_CHALLENGE = -1
    GAMEOPTION_NO_CHANGING_WAR_PEACE = -1
    GAMEOPTION_NEW_RANDOM_SEED = -1
    GAMEOPTION_LOCK_MODS = -1
    GAMEOPTION_COMPLETE_KILLS = -1
    GAMEOPTION_NO_VASSAL_STATES = -1
    GAMEOPTION_NO_GOODY_HUTS = -1
    GAMEOPTION_NO_EVENTS = -1
    GAMEOPTION_NO_ESPIONAGE = -1
    NUM_GAMEOPTION_TYPES = -1

class MultiplayerOptionTypes(Enum):
    NO_MPOPTION = -1
    MPOPTION_SIMULTANEOUS_TURNS = -1
    MPOPTION_TAKEOVER_AI = -1
    MPOPTION_SHUFFLE_TEAMS = -1
    MPOPTION_ANONYMOUS = -1
    MPOPTION_TURN_TIMER = -1
    NUM_MPOPTION_TYPES = -1

class SpecialOptionTypes(Enum):
    NO_SPECIALOPTION = -1
    SPECIALOPTION_REPORT_STATS = -1
    NUM_SPECIALOPTION_TYPES = -1

class PlayerOptionTypes(Enum):
    NO_PLAYEROPTION = -1
    PLAYEROPTION_ADVISOR_POPUPS = -1
    PLAYEROPTION_ADVISOR_HELP = -1
    PLAYEROPTION_WAIT_END_TURN = -1
    PLAYEROPTION_MINIMIZE_POP_UPS = -1
    PLAYEROPTION_SHOW_FRIENDLY_MOVES = -1
    PLAYEROPTION_SHOW_ENEMY_MOVES = -1
    PLAYEROPTION_QUICK_MOVES = -1
    PLAYEROPTION_QUICK_ATTACK = -1
    PLAYEROPTION_QUICK_DEFENSE = -1
    PLAYEROPTION_STACK_ATTACK = -1
    PLAYEROPTION_AUTO_PROMOTION = -1
    PLAYEROPTION_START_AUTOMATED = -1
    PLAYEROPTION_SAFE_AUTOMATION = -1
    PLAYEROPTION_NUMPAD_HELP = -1
    PLAYEROPTION_NO_UNIT_CYCLING = -1
    PLAYEROPTION_NO_UNIT_RECOMMENDATIONS = -1
    PLAYEROPTION_RIGHT_CLICK_MENU = -1
    PLAYEROPTION_LEAVE_FORESTS = -1
    PLAYEROPTION_MISSIONARIES_AUTOMATED = -1
    PLAYEROPTION_MODDER_1 = -1
    PLAYEROPTION_MODDER_2 = -1
    PLAYEROPTION_MODDER_3 = -1
    NUM_PLAYEROPTION_TYPES = -1

class GraphicOptionTypes(Enum):
    NO_GRAPHICOPTION = -1
    GRAPHICOPTION_SINGLE_UNIT_GRAPHICS = -1
    GRAPHICOPTION_HEALTH_BARS = -1
    GRAPHICOPTION_CITY_DETAIL = -1
    GRAPHICOPTION_NO_COMBAT_ZOOM = -1
    GRAPHICOPTION_NO_ENEMY_GLOW = -1
    GRAPHICOPTION_FROZEN_ANIMATIONS = -1
    GRAPHICOPTION_EFFECTS_DISABLED = -1
    GRAPHICOPTION_GLOBE_VIEW_BUILDINGS_DISABLED = -1
    GRAPHICOPTION_FULLSCREEN = -1
    GRAPHICOPTION_LOWRES_TEXTURES = -1
    GRAPHICOPTION_HIRES_TERRAIN = -1
    GRAPHICOPTION_NO_MOVIES = -1
    GRAPHICOPTION_CITY_RADIUS = -1
    NUM_GRAPHICOPTION_TYPES = -1

class ForceControlTypes(Enum):
    NO_FORCECONTROL = -1
    FORCECONTROL_SPEED = -1
    FORCECONTROL_HANDICAP = -1
    FORCECONTROL_OPTIONS = -1
    FORCECONTROL_VICTORIES = -1
    FORCECONTROL_MAX_TURNS = -1
    FORCECONTROL_MAX_CITY_ELIMINATIONS = -1
    FORCECONTROL_ADVANCED_START = -1
    NUM_FORCECONTROL_TYPES = -1

class VictoryTypes(Enum):
    NO_VICTORY = -1

class FeatureTypes(Enum):
    NO_FEATURE = -1

class BonusTypes(Enum):
    NO_BONUS = -1

class BonusClassTypes(Enum):
    NO_BONUSCLASS = -1

class ImprovementTypes(Enum):
    NO_IMPROVEMENT = -1

class RouteTypes(Enum):
    NO_ROUTE = -1

class RiverTypes(Enum):
    NO_RIVER = -1

class GoodyTypes(Enum):
    NO_GOODY = -1

class BuildTypes(Enum):
    NO_BUILD = -1

class SymbolTypes(Enum):
    NO_SYMBOL = -1

class FontSymbols(Enum):
    HAPPY_CHAR = -1
    UNHAPPY_CHAR = -1
    HEALTHY_CHAR = -1
    UNHEALTHY_CHAR = -1
    BULLET_CHAR = -1
    STRENGTH_CHAR = -1
    MOVES_CHAR = -1
    RELIGION_CHAR = -1
    STAR_CHAR = -1
    SILVER_STAR_CHAR = -1
    TRADE_CHAR = -1
    DEFENSE_CHAR = -1
    GREAT_PEOPLE_CHAR = -1
    BAD_GOLD_CHAR = -1
    BAD_FOOD_CHAR = -1
    EATEN_FOOD_CHAR = -1
    GOLDEN_AGE_CHAR = -1
    ANGRY_POP_CHAR = -1
    OPEN_BORDERS_CHAR = -1
    DEFENSIVE_PACT_CHAR = -1
    MAP_CHAR = -1
    OCCUPATION_CHAR = -1
    POWER_CHAR = -1
    MAX_NUM_SYMBOLS = -1

class HandicapTypes(Enum):
    NO_HANDICAP = -1

class GameSpeedTypes(Enum):
    NO_GAMESPEED = -1

class TurnTimerTypes(Enum):
    NO_TURNTIMER = -1

class EraTypes(Enum):
    NO_ERA = -1

class CivilizationTypes(Enum):
    NO_CIVILIZATION = -1

class LeaderHeadTypes(Enum):
    NO_LEADER = -1

class ArtStyleTypes(Enum):
    NO_ARTSTYLE = -1

class CitySizeTypes(Enum):
    NO_CITYSIZE = -1
    CITYSIZE_SMALL = -1
    CITYSIZE_MEDIUM = -1
    CITYSIZE_LARGE = -1
    NUM_CITYSIZE_TYPES = -1

class FootstepAudioTypes(Enum):
    NO_FOOTSTEPAUDIO = -1

class FootstepAudioTags(Enum):
    NO_FOOTSTEPAUDIO_TAG = -1

class ChatTargetTypes(Enum):
    NO_CHATTARGET = -1
    CHATTARGET_ALL = -1
    CHATTARGET_TEAM = -1

class VoiceTargetTypes(Enum):
    NO_VOICETARGET = -1
    VOICETARGET_DIPLO = -1
    VOICETARGET_TEAM = -1
    VOICETARGET_ALL = -1
    NUM_VOICETARGETS = -1

class TeamTypes(Enum):
    NO_TEAM = -1

class PlayerTypes(Enum):
    NO_PLAYER = -1

class TraitTypes(Enum):
    NO_TRAIT = -1

class OrderTypes(Enum):
    NO_ORDER = -1
    ORDER_TRAIN = -1
    ORDER_CONSTRUCT = -1
    ORDER_CREATE = -1
    ORDER_MAINTAIN = -1
    NUM_ORDER_TYPES = -1

class TaskTypes(Enum):
    TASK_RAZE = -1
    TASK_DISBAND = -1
    TASK_GIFT = -1
    TASK_SET_AUTOMATED_CITIZENS = -1
    TASK_SET_AUTOMATED_PRODUCTION = -1
    TASK_SET_EMPHASIZE = -1
    TASK_CHANGE_SPECIALIST = -1
    TASK_CHANGE_WORKING_PLOT = -1
    TASK_CLEAR_WORKING_OVERRIDE = -1
    TASK_HURRY = -1
    TASK_CONSCRIPT = -1
    TASK_CLEAR_ORDERS = -1
    TASK_RALLY_PLOT = -1
    TASK_CLEAR_RALLY_PLOT = -1
    TASK_LIBERATE = -1
    NUM_TASK_TYPES = -1

class BuildingClassTypes(Enum):
    NO_BUILDINGCLASS = -1

class BuildingTypes(Enum):
    NO_BUILDING = -1

class SpecialBuildingTypes(Enum):
    NO_SPECIALBUILDING = -1

class ProjectTypes(Enum):
    NO_PROJECT = -1

class ProcessTypes(Enum):
    NO_PROCESS = -1

class VoteTypes(Enum):
    NO_VOTE = -1

class PlayerVoteTypes(Enum):
    NO_PLAYER_VOTE_CHECKED = -1
    PLAYER_VOTE_NEVER = -1
    PLAYER_VOTE_ABSTAIN = -1
    PLAYER_VOTE_NO = -1
    PLAYER_VOTE_YES = -1
    NO_PLAYER_VOTE = -1

class InfoBarTypes(Enum):
    INFOBAR_STORED = -1
    INFOBAR_RATE = -1
    INFOBAR_RATE_EXTRA = -1
    INFOBAR_EMPTY = -1
    NUM_INFOBAR_TYPES = -1

class HealthBarTypes(Enum):
    HEALTHBAR_ALIVE_ATTACK = -1
    HEALTHBAR_ALIVE_DEFEND = -1
    HEALTHBAR_DEAD = -1
    NUM_HEALTHBAR_TYPES = -1

class ConceptTypes(Enum):
    NO_CONCEPT = -1

class NewConceptTypes(Enum):
    NO_NEW_CONCEPT = -1

class CalendarTypes(Enum):
    CALENDAR_DEFAULT = -1
    CALENDAR_BI_YEARLY = -1
    CALENDAR_YEARS = -1
    CALENDAR_TURNS = -1
    CALENDAR_SEASONS = -1
    CALENDAR_MONTHS = -1
    CALENDAR_WEEKS = -1

class SeasonTypes(Enum):
    NO_SEASON = -1

class MonthTypes(Enum):
    NO_MONTH = -1

class DenialTypes(Enum):
    NO_DENIAL = -1
    DENIAL_UNKNOWN = -1
    DENIAL_NEVER = -1
    DENIAL_TOO_MUCH = -1
    DENIAL_MYSTERY = -1
    DENIAL_JOKING = -1
    DENIAL_ANGER_CIVIC = -1
    DENIAL_FAVORITE_CIVIC = -1
    DENIAL_MINORITY_RELIGION = -1
    DENIAL_CONTACT_THEM = -1
    DENIAL_VICTORY = -1
    DENIAL_ATTITUDE = -1
    DENIAL_ATTITUDE_THEM = -1
    DENIAL_TECH_WHORE = -1
    DENIAL_TECH_MONOPOLY = -1
    DENIAL_POWER_US = -1
    DENIAL_POWER_YOU = -1
    DENIAL_POWER_THEM = -1
    DENIAL_TOO_MANY_WARS = -1
    DENIAL_NO_GAIN = -1
    DENIAL_NOT_ALLIED = -1
    DENIAL_RECENT_CANCEL = -1
    DENIAL_WORST_ENEMY = -1
    DENIAL_POWER_YOUR_ENEMIES = -1
    DENIAL_TOO_FAR = -1

class DomainTypes(Enum):
    DOMAIN_SEA = -1
    DOMAIN_AIR = -1
    DOMAIN_LAND = -1
    DOMAIN_IMMOBILE = -1
    DOMAIN_HELICOPTER = -1
    NUM_DOMAIN_TYPES = -1

class UnitClassTypes(Enum):
    NO_UNITCLASS = -1

class UnitTypes(Enum):
    NO_UNIT = -1

class SpecialUnitTypes(Enum):
    NO_SPECIALUNIT = -1

class UnitCombatTypes(Enum):
    NO_UNITCOMBAT = -1

class UnitAITypes(Enum):
    NO_UNITAI = -1
    UNITAI_UNKNOWN = -1
    UNITAI_ANIMAL = -1
    UNITAI_SETTLE = -1
    UNITAI_WORKER = -1
    UNITAI_ATTACK = -1
    UNITAI_ATTACK_CITY = -1
    UNITAI_COLLATERAL = -1
    UNITAI_PILLAGE = -1
    UNITAI_RESERVE = -1
    UNITAI_COUNTER = -1
    UNITAI_CITY_DEFENSE = -1
    UNITAI_CITY_COUNTER = -1
    UNITAI_CITY_SPECIAL = -1
    UNITAI_EXPLORE = -1
    UNITAI_MISSIONARY = -1
    UNITAI_PROPHET = -1
    UNITAI_ARTIST = -1
    UNITAI_SCIENTIST = -1
    UNITAI_GENERAL = -1
    UNITAI_MERCHANT = -1
    UNITAI_ENGINEER = -1
    UNITAI_SPY = -1
    UNITAI_ICBM = -1
    UNITAI_WORKER_SEA = -1
    UNITAI_ATTACK_SEA = -1
    UNITAI_RESERVE_SEA = -1
    UNITAI_ESCORT_SEA = -1
    UNITAI_EXPLORE_SEA = -1
    UNITAI_ASSAULT_SEA = -1
    UNITAI_SETTLER_SEA = -1
    UNITAI_MISSIONARY_SEA = -1
    UNITAI_SPY_SEA = -1
    UNITAI_CARRIER_SEA = -1
    UNITAI_MISSILE_CARRIER_SEA = -1
    UNITAI_PIRATE_SEA = -1
    UNITAI_ATTACK_AIR = -1
    UNITAI_DEFENSE_AIR = -1
    UNITAI_CARRIER_AIR = -1
    UNITAI_MISSILE_AIR = -1
    UNITAI_PARADROP = -1
    UNITAI_ATTACK_CITY_LEMMING = -1
    NUM_UNITAI_TYPES = -1

class InvisibleTypes(Enum):
    NO_INVISIBLE = -1

class VoteSourceTypes(Enum):
    NO_VOTESOURCE = -1

class ProbabilityTypes(Enum):
    NO_PROBABILITY = -1
    PROBABILITY_LOW = -1
    PROBABILITY_REAL = -1
    PROBABILITY_HIGH = -1

class ActivityTypes(Enum):
    NO_ACTIVITY = -1
    ACTIVITY_AWAKE = -1
    ACTIVITY_HOLD = -1
    ACTIVITY_SLEEP = -1
    ACTIVITY_HEAL = -1
    ACTIVITY_SENTRY = -1
    ACTIVITY_INTERCEPT = -1
    ACTIVITY_MISSION = -1
    ACTIVITY_PATROL = -1
    ACTIVITY_PLUNDER = -1
    NUM_ACTIVITY_TYPES = -1

class AutomateTypes(Enum):
    NO_AUTOMATE = -1
    AUTOMATE_BUILD = -1
    AUTOMATE_NETWORK = -1
    AUTOMATE_CITY = -1
    AUTOMATE_EXPLORE = -1
    AUTOMATE_RELIGION = -1
    NUM_AUTOMATE_TYPES = -1

class MissionTypes(Enum):
    NO_MISSION = -1
    MISSION_MOVE_TO = -1
    MISSION_ROUTE_TO = -1
    MISSION_MOVE_TO_UNIT = -1
    MISSION_SKIP = -1
    MISSION_SLEEP = -1
    MISSION_FORTIFY = -1
    MISSION_PLUNDER = -1
    MISSION_AIRPATROL = -1
    MISSION_SEAPATROL = -1
    MISSION_HEAL = -1
    MISSION_SENTRY = -1
    MISSION_AIRLIFT = -1
    MISSION_NUKE = -1
    MISSION_RECON = -1
    MISSION_PARADROP = -1
    MISSION_AIRBOMB = -1
    MISSION_RANGE_ATTACK = -1
    MISSION_BOMBARD = -1
    MISSION_PILLAGE = -1
    MISSION_SABOTAGE = -1
    MISSION_DESTROY = -1
    MISSION_STEAL_PLANS = -1
    MISSION_FOUND = -1
    MISSION_SPREAD = -1
    MISSION_SPREAD_CORPORATION = -1
    MISSION_JOIN = -1
    MISSION_CONSTRUCT = -1
    MISSION_DISCOVER = -1
    MISSION_HURRY = -1
    MISSION_TRADE = -1
    MISSION_GREAT_WORK = -1
    MISSION_INFILTRATE = -1
    MISSION_LEAD = -1
    MISSION_ESPIONAGE = -1
    MISSION_GOLDEN_AGE = -1
    MISSION_BUILD = -1
    MISSION_BEGIN_COMBAT = -1
    MISSION_END_COMBAT = -1
    MISSION_AIRSTRIKE = -1
    MISSION_SURRENDER = -1
    MISSION_CAPTURED = -1
    MISSION_IDLE = -1
    MISSION_DIE = -1
    MISSION_DAMAGE = -1
    MISSION_MULTI_SELECT = -1
    MISSION_MULTI_DESELECT = -1
    NUM_MISSION_TYPES = -1

class MissionAITypes(Enum):
    NO_MISSIONAI = -1
    MISSIONAI_SHADOW = -1
    MISSIONAI_GROUP = -1
    MISSIONAI_LOAD_ASSAULT = -1
    MISSIONAI_LOAD_SETTLER = -1
    MISSIONAI_LOAD_SPECIAL = -1
    MISSIONAI_GUARD_CITY = -1
    MISSIONAI_GUARD_BONUS = -1
    MISSIONAI_GUARD_TRADE_NET = -1
    MISSIONAI_GUARD_SPY = -1
    MISSIONAI_ATTACK_SPY = -1
    MISSIONAI_SPREAD = -1
    MISSIONAI_SPREAD_CORPORATION = -1
    MISSIONAI_CONSTRUCT = -1
    MISSIONAI_HURRY = -1
    MISSIONAI_GREAT_WORK = -1
    MISSIONAI_EXPLORE = -1
    MISSIONAI_BLOCKADE = -1
    MISSIONAI_PILLAGE = -1
    MISSIONAI_FOUND = -1
    MISSIONAI_BUILD = -1
    MISSIONAI_ASSAULT = -1
    MISSIONAI_CARRIER = -1
    MISSIONAI_PICKUP = -1

class CommandTypes(Enum):
    NO_COMMAND = -1
    COMMAND_PROMOTION = -1
    COMMAND_UPGRADE = -1
    COMMAND_AUTOMATE = -1
    COMMAND_WAKE = -1
    COMMAND_CANCEL = -1
    COMMAND_CANCEL_ALL = -1
    COMMAND_STOP_AUTOMATION = -1
    COMMAND_DELETE = -1
    COMMAND_GIFT = -1
    COMMAND_LOAD = -1
    COMMAND_LOAD_UNIT = -1
    COMMAND_UNLOAD = -1
    COMMAND_UNLOAD_ALL = -1
    COMMAND_HOTKEY = -1
    NUM_COMMAND_TYPES = -1

class ControlTypes(Enum):
    NO_CONTROL = -1
    CONTROL_CENTERONSELECTION = -1
    CONTROL_SELECTYUNITTYPE = -1
    CONTROL_SELECTYUNITALL = -1
    CONTROL_SELECTCITY = -1
    CONTROL_SELECTCAPITAL = -1
    CONTROL_NEXTCITY = -1
    CONTROL_PREVCITY = -1
    CONTROL_NEXTUNIT = -1
    CONTROL_PREVUNIT = -1
    CONTROL_CYCLEUNIT = -1
    CONTROL_CYCLEUNIT_ALT = -1
    CONTROL_CYCLEWORKER = -1
    CONTROL_LASTUNIT = -1
    CONTROL_ENDTURN = -1
    CONTROL_ENDTURN_ALT = -1
    CONTROL_FORCEENDTURN = -1
    CONTROL_AUTOMOVES = -1
    CONTROL_PING = -1
    CONTROL_SIGN = -1
    CONTROL_GRID = -1
    CONTROL_BARE_MAP = -1
    CONTROL_YIELDS = -1
    CONTROL_RESOURCE_ALL = -1
    CONTROL_UNIT_ICONS = -1
    CONTROL_GLOBELAYER = -1
    CONTROL_SCORES = -1
    CONTROL_LOAD_GAME = -1
    CONTROL_OPTIONS_SCREEN = -1
    CONTROL_RETIRE = -1
    CONTROL_SAVE_GROUP = -1
    CONTROL_SAVE_NORMAL = -1
    CONTROL_QUICK_SAVE = -1
    CONTROL_QUICK_LOAD = -1
    CONTROL_ORTHO_CAMERA = -1
    CONTROL_CYCLE_CAMERA_FLYING_MODES = -1
    CONTROL_ISOMETRIC_CAMERA_LEFT = -1
    CONTROL_ISOMETRIC_CAMERA_RIGHT = -1
    CONTROL_FLYING_CAMERA = -1
    CONTROL_MOUSE_FLYING_CAMERA = -1
    CONTROL_TOP_DOWN_CAMERA = -1
    CONTROL_CIVILOPEDIA = -1
    CONTROL_RELIGION_SCREEN = -1
    CONTROL_CORPORATION_SCREEN = -1
    CONTROL_CIVICS_SCREEN = -1
    CONTROL_FOREIGN_SCREEN = -1
    CONTROL_FINANCIAL_SCREEN = -1
    CONTROL_MILITARY_SCREEN = -1
    CONTROL_TECH_CHOOSER = -1
    CONTROL_TURN_LOG = -1
    CONTROL_CHAT_ALL = -1
    CONTROL_CHAT_TEAM = -1
    CONTROL_DOMESTIC_SCREEN = -1
    CONTROL_VICTORY_SCREEN = -1
    CONTROL_INFO = -1
    CONTROL_GLOBE_VIEW = -1
    CONTROL_DETAILS = -1
    CONTROL_ADMIN_DETAILS = -1
    CONTROL_HALL_OF_FAME = -1
    CONTROL_WORLD_BUILDER = -1
    CONTROL_DIPLOMACY = -1
    CONTROL_SELECT_HEALTHY = -1
    CONTROL_ESPIONAGE_SCREEN = -1
    CONTROL_FREE_COLONY = -1

    NUM_CONTROL_TYPES = -1

class PromotionTypes(Enum):
    NO_PROMOTION = -1

class TechTypes(Enum):
    NO_TECH = -1

class SpecialistTypes(Enum):
    NO_SPECIALIST = -1

class ReligionTypes(Enum):
    NO_RELIGION = -1

class CorporationTypes(Enum):
    NO_CORPORATION = -1

class HurryTypes(Enum):
    NO_HURRY = -1

class UpkeepTypes(Enum):
    NO_UPKEEP = -1

class CultureLevelTypes(Enum):
    NO_CULTURELEVEL = -1

class CivicOptionTypes(Enum):
    NO_CIVICOPTION = -1

class CivicTypes(Enum):
    NO_CIVIC = -1

class WarPlanTypes(Enum):
    NO_WARPLAN = -1
    WARPLAN_ATTACKED_RECENT = -1
    WARPLAN_ATTACKED = -1
    WARPLAN_PREPARING_LIMITED = -1
    WARPLAN_PREPARING_TOTAL = -1
    WARPLAN_LIMITED = -1
    WARPLAN_TOTAL = -1
    WARPLAN_DOGPILE = -1

class AreaAITypes(Enum):
    NO_AREAAI = -1
    AREAAI_OFFENSIVE = -1
    AREAAI_DEFENSIVE = -1
    AREAAI_MASSING = -1
    AREAAI_ASSAULT = -1
    AREAAI_NEUTRAL = -1

class EndTurnButtonStates(Enum):
    END_TURN_GO = -1
    END_TURN_OVER_HIGHLIGHT = -1
    END_TURN_OVER_DARK = -1
    NUM_END_TURN_STATES = -1

class FogOfWarModeTypes(Enum):
    FOGOFWARMODE_OFF = -1
    FOGOFWARMODE_UNEXPLORED = -1
    NUM_FOGOFWARMODE_TYPES = -1

class AnimationTypes(Enum):
    NONE_ANIMATION = -1
    BONUSANIMATION_UNIMPROVED = -1
    BONUSANIMATION_NOT_WORKED = -1
    BONUSANIMATION_WORKED = -1
    IMPROVEMENTANIMATION_OFF = -1
    IMPROVEMENTANIMATION_ON = -1
    IMPROVEMENTANIMATION_OFF_EXTRA = -1
    IMPROVEMENTANIMATION_ON_EXTRA_1 = -1
    IMPROVEMENTANIMATION_ON_EXTRA_2 = -1
    IMPROVEMENTANIMATION_ON_EXTRA_3 = -1
    IMPROVEMENTANIMATION_ON_EXTRA_4 = -1

class EntityEventTypes(Enum):
    ENTITY_EVENT_NONE = -1
    ENTEVENT_MOVE = 1

class AnimationPathTypes(Enum):
    ANIMATIONPATH_NONE = -1
    ANIMATIONPATH_IDLE = -1
    ANIMATIONPATH_MOVE = -1
    ANIMATIONPATH_RANDOMIZE_ANIMATION_SET = -1
    ANIMATIONPATH_NUKE_STRIKE = -1
    ANIMATIONPATH_MELEE_STRIKE = -1
    ANIMATIONPATH_MELEE_HURT = -1
    ANIMATIONPATH_MELEE_DIE = -1
    ANIMATIONPATH_MELEE_FORTIFIED = -1
    ANIMATIONPATH_MELEE_DIE_FADE = -1
    ANIMATIONPATH_RANGED_STRIKE = -1
    ANIMATIONPATH_RANGED_DIE = -1
    ANIMATIONPATH_RANGED_FORTIFIED = -1
    ANIMATIONPATH_RANGED_RUNHIT = -1
    ANIMATIONPATH_RANGED_RUNDIE = -1
    ANIMATIONPATH_RANGED_DIE_FADE = -1
    ANIMATIONPATH_LEADER_COMMAND = -1
    ANIMATIONPATH_AIRFADEIN = -1
    ANIMATIONPATH_AIRFADEOUT = -1
    ANIMATIONPATH_AIRSTRIKE = -1
    ANIMATIONPATH_AIRBOMB = -1
    ANIMATIONPATH_RUN = -1

class AnimationCategoryTypes(Enum):
    ANIMCAT_NONE = -1

class CursorTypes(Enum):
    NO_CURSOR = -1

class TradeableItems(Enum):
    NO_TRADEABLE_ITEMS = -1
    TRADE_GOLD = -1
    TRADE_GOLD_PER_TURN = -1
    TRADE_MAPS = -1
    TRADE_VASSAL = -1
    TRADE_SURRENDER = -1
    TRADE_OPEN_BORDERS = -1
    TRADE_DEFENSIVE_PACT = -1
    TRADE_PERMANENT_ALLIANCE = -1
    TRADE_PEACE_TREATY = -1
    NUM_BASIC_ITEMS = -1
    TRADE_TECHNOLOGIES = -1
    TRADE_RESOURCES = -1
    TRADE_CITIES = -1
    TRADE_PEACE = -1
    TRADE_WAR = -1
    TRADE_EMBARGO = -1
    TRADE_CIVIC = -1
    TRADE_RELIGION = -1
    NUM_TRADEABLE_HEADINGS = -1
    NUM_TRADEABLE_ITEMS = -1

class DiploEventTypes(Enum):
    NO_DIPLOEVENT = -1
    DIPLOEVENT_CONTACT = -1
    DIPLOEVENT_AI_CONTACT = -1
    DIPLOEVENT_FAILED_CONTACT = -1
    DIPLOEVENT_GIVE_HELP = -1
    DIPLOEVENT_REFUSED_HELP = -1
    DIPLOEVENT_ACCEPT_DEMAND = -1
    DIPLOEVENT_REJECTED_DEMAND = -1
    DIPLOEVENT_DEMAND_WAR = -1
    DIPLOEVENT_CONVERT = -1
    DIPLOEVENT_NO_CONVERT = -1
    DIPLOEVENT_REVOLUTION = -1
    DIPLOEVENT_NO_REVOLUTION = -1
    DIPLOEVENT_JOIN_WAR = -1
    DIPLOEVENT_NO_JOIN_WAR = -1
    DIPLOEVENT_STOP_TRADING = -1
    DIPLOEVENT_NO_STOP_TRADING = -1
    DIPLOEVENT_ASK_HELP = -1
    DIPLOEVENT_MADE_DEMAND = -1
    DIPLOEVENT_RESEARCH_TECH = -1
    DIPLOEVENT_TARGET_CITY = -1
    DIPLOEVENT_MADE_DEMAND_VASSAL = -1
    NUM_DIPLOEVENT_TYPES = -1

class DiploCommentTypes(Enum):
    NO_DIPLOCOMMENT = -1

class NetContactTypes(Enum):
    NO_NETCONTACT = -1
    NETCONTACT_INITIAL = -1
    NETCONTACT_RESPONSE = -1
    NETCONTACT_ESTABLISHED = -1
    NETCONTACT_BUSY = -1
    NUM_NETCONTACT_TYPES = -1

class ContactTypes(Enum):
    CONTACT_RELIGION_PRESSURE = -1
    CONTACT_CIVIC_PRESSURE = -1
    CONTACT_JOIN_WAR = -1
    CONTACT_STOP_TRADING = -1
    CONTACT_GIVE_HELP = -1
    CONTACT_ASK_FOR_HELP = -1
    CONTACT_DEMAND_TRIBUTE = -1
    CONTACT_OPEN_BORDERS = -1
    CONTACT_DEFENSIVE_PACT = -1
    CONTACT_PERMANENT_ALLIANCE = -1
    CONTACT_PEACE_TREATY = -1
    CONTACT_TRADE_TECH = -1
    CONTACT_TRADE_BONUS = -1
    CONTACT_TRADE_MAP = -1
    NUM_CONTACT_TYPES = -1

class MemoryTypes(Enum):
    MEMORY_DECLARED_WAR = -1
    MEMORY_DECLARED_WAR_ON_FRIEND = -1
    MEMORY_HIRED_WAR_ALLY = -1
    MEMORY_NUKED_US = -1
    MEMORY_NUKED_FRIEND = -1
    MEMORY_RAZED_CITY = -1
    MEMORY_RAZED_HOLY_CITY = -1
    MEMORY_SPY_CAUGHT = -1
    MEMORY_GIVE_HELP = -1
    MEMORY_REFUSED_HELP = -1
    MEMORY_ACCEPT_DEMAND = -1
    MEMORY_REJECTED_DEMAND = -1
    MEMORY_ACCEPTED_RELIGION = -1
    MEMORY_DENIED_RELIGION = -1
    MEMORY_ACCEPTED_CIVIC = -1
    MEMORY_DENIED_CIVIC = -1
    MEMORY_ACCEPTED_JOIN_WAR = -1
    MEMORY_DENIED_JOIN_WAR = -1
    MEMORY_ACCEPTED_STOP_TRADING = -1
    MEMORY_DENIED_STOP_TRADING = -1
    MEMORY_STOPPED_TRADING = -1
    MEMORY_STOPPED_TRADING_RECENT = -1
    MEMORY_HIRED_TRADE_EMBARGO = -1
    MEMORY_MADE_DEMAND = -1
    MEMORY_MADE_DEMAND_RECENT = -1
    MEMORY_CANCELLED_OPEN_BORDERS = -1
    MEMORY_TRADED_TECH_TO_US = -1
    MEMORY_RECEIVED_TECH_FROM_ANY = -1
    MEMORY_VOTED_AGAINST_US = -1
    MEMORY_VOTED_FOR_US = -1
    MEMORY_EVENT_GOOD_TO_US = -1
    MEMORY_EVENT_BAD_TO_US = -1
    MEMORY_LIBERATED_CITIES = -1
    NUM_MEMORY_TYPES = -1

class AttitudeTypes(Enum):
    NO_ATTITUDE = -1
    ATTITUDE_FURIOUS = -1
    ATTITUDE_ANNOYED = -1
    ATTITUDE_CAUTIOUS = -1
    ATTITUDE_PLEASED = -1
    ATTITUDE_FRIENDLY = -1
    NUM_ATTITUDE_TYPES = -1

class LeaderheadAction(Enum):
    NO_LEADERANIM = -1
    LEADERANIM_GREETING = -1
    LEADERANIM_FRIENDLY = -1
    LEADERANIM_PLEASED = -1
    LEADERANIM_CAUTIOUS = -1
    LEADERANIM_ANNOYED = -1
    LEADERANIM_FURIOUS = -1
    LEADERANIM_DISAGREE = -1
    LEADERANIM_AGREE = -1
    NUM_LEADERANIM_TYPES = -1

class DiplomacyPowerTypes(Enum):
    NO_DIPLOMACYPOWER = -1
    DIPLOMACYPOWER_WEAKER = -1
    DIPLOMACYPOWER_EQUAL = -1
    DIPLOMACYPOWER_STRONGER = -1
    NUM_DIPLOMACYPOWER_TYPES = -1

class FeatTypes(Enum):
    FEAT_UNITCOMBAT_ARCHER = -1
    FEAT_UNITCOMBAT_MOUNTED = -1
    FEAT_UNITCOMBAT_MELEE = -1
    FEAT_UNITCOMBAT_SIEGE = -1
    FEAT_UNITCOMBAT_GUN = -1
    FEAT_UNITCOMBAT_ARMOR = -1
    FEAT_UNITCOMBAT_HELICOPTER = -1
    FEAT_UNITCOMBAT_NAVAL = -1
    FEAT_UNIT_PRIVATEER = -1
    FEAT_UNIT_SPY = -1
    FEAT_NATIONAL_WONDER = -1
    FEAT_TRADE_ROUTE = -1
    FEAT_COPPER_CONNECTED = -1
    FEAT_HORSE_CONNECTED = -1
    FEAT_IRON_CONNECTED = -1
    FEAT_LUXURY_CONNECTED = -1
    FEAT_FOOD_CONNECTED = -1
    FEAT_POPULATION_HALF_MILLION = -1
    FEAT_POPULATION_1_MILLION = -1
    FEAT_POPULATION_2_MILLION = -1
    FEAT_POPULATION_5_MILLION = -1
    FEAT_POPULATION_10_MILLION = -1
    FEAT_POPULATION_20_MILLION = -1
    FEAT_POPULATION_50_MILLION = -1
    FEAT_POPULATION_100_MILLION = -1
    FEAT_POPULATION_200_MILLION = -1
    FEAT_POPULATION_500_MILLION = -1
    FEAT_POPULATION_1_BILLION = -1
    FEAT_POPULATION_2_BILLION = -1
    FEAT_CORPORATION_ENABLED = -1
    FEAT_PAD = -1
    NUM_FEAT_TYPES = -1

class SaveGameTypes(Enum):
    SAVEGAME_NONE = -1
    SAVEGAME_AUTO = -1
    SAVEGAME_RECOVERY = -1
    SAVEGAME_QUICK = -1
    SAVEGAME_NORMAL = -1
    SAVEGAME_GROUP = -1
    SAVEGAME_DROP_QUIT = -1
    SAVEGAME_DROP_CONTINUE = -1
    SAVEGAME_PBEM = -1
    SAVEGAME_REPLAY = -1
    NUM_SAVEGAME_TYPES = -1

class GameType(Enum):
    GAME_NONE = -1
    GAME_SP_NEW = -1
    GAME_SP_SCENARIO = -1
    GAME_SP_LOAD = -1
    GAME_MP_NEW = -1
    GAME_MP_SCENARIO = -1
    GAME_MP_LOAD = -1
    GAME_HOTSEAT_NEW = -1
    GAME_HOTSEAT_SCENARIO = -1
    GAME_HOTSEAT_LOAD = -1
    GAME_PBEM_NEW = -1
    GAME_PBEM_SCENARIO = -1
    GAME_PBEM_LOAD = -1
    GAME_REPLAY = -1
    NUM_GAMETYPES = -1

class GameMode(Enum):
    NO_GAMEMODE = -1
    GAMEMODE_NORMAL = -1
    GAMEMODE_PITBOSS = -1
    NUM_GAMEMODES = -1

class InterfaceVisibility(Enum):
    INTERFACE_SHOW = -1
    INTERFACE_HIDE = -1
    INTERFACE_HIDE_ALL = -1
    INTERFACE_MINIMAP_ONLY = -1
    INTERFACE_ADVANCED_START = -1

class GenericButtonSizes(Enum):
    BUTTON_SIZE_46 = -1
    BUTTON_SIZE_32 = -1
    BUTTON_SIZE_24 = -1
    BUTTON_SIZE_16 = -1
    BUTTON_SIZE_CUSTOM = -1

class WorldBuilderPopupTypes(Enum):
    WBPOPUP_NONE = -1
    WBPOPUP_START = -1
    WBPOPUP_CITY = -1
    WBPOPUP_UNIT = -1
    WBPOPUP_PLAYER = -1
    WBPOPUP_PLOT = -1
    WBPOPUP_TERRAIN = -1
    WBPOPUP_FEATURE = -1
    WBPOPUP_IMPROVEMENT = -1
    WBPOPUP_GAME = -1
    NUM_WBPOPUP = -1

class EventType(Enum):
    EVT_LBUTTONDOWN = -1
    EVT_LBUTTONDBLCLICK = -1
    EVT_RBUTTONDOWN = -1
    EVT_BACK = -1
    EVT_FORWARD = -1
    EVT_KEYDOWN = -1
    EVT_KEYUP = -1

class LoadType(Enum):
    LOAD_NORMAL = -1
    LOAD_INIT = -1
    LOAD_SETUP = -1
    LOAD_GAMETYPE = -1
    LOAD_REPLAY = -1

class FontTypes(Enum):
    TITLE_FONT = -1
    GAME_FONT = -1
    SMALL_FONT = -1
    MENU_FONT = -1
    MENU_HIGHLIGHT_FONT = -1

class PanelStyles(Enum):
    PANEL_STYLE_STANDARD = -1
    PANEL_STYLE_SOLID = -1
    PANEL_STYLE_EMPTY = -1
    PANEL_STYLE_FLAT = -1
    PANEL_STYLE_IN = -1
    PANEL_STYLE_OUT = -1
    PANEL_STYLE_EXTERNAL = -1
    PANEL_STYLE_DEFAULT = -1

    PANEL_STYLE_CIVILPEDIA = -1
    PANEL_STYLE_STONE = -1
    PANEL_STYLE_BLUELARGE = -1
    PANEL_STYLE_UNITSTAT = -1
    PANEL_STYLE_BLUE50 = -1

    PANEL_STYLE_TOPBAR = -1
    PANEL_STYLE_BOTTOMBAR = -1
    PANEL_STYLE_TECH = -1

    PANEL_STYLE_GAMEHUD_LEFT = -1
    PANEL_STYLE_GAMEHUD_RIGHT = -1
    PANEL_STYLE_GAMEHUD_CENTER = -1
    PANEL_STYLE_GAMEHUD_STATS = -1
    PANEL_STYLE_GAME_MAP = -1
    PANEL_STYLE_GAME_TOPBAR = -1
    PANEL_STYLE_HUD_HELP = -1

    PANEL_STYLE_CITY_LEFT = -1
    PANEL_STYLE_CITY_RIGHT = -1
    PANEL_STYLE_CITY_TOP = -1
    PANEL_STYLE_CITY_TANSHADE = -1
    PANEL_STYLE_CITY_INFO = -1
    PANEL_STYLE_CITY_TANTL = -1
    PANEL_STYLE_CITY_TANTR = -1
    PANEL_STYLE_CITY_COLUMNL = -1
    PANEL_STYLE_CITY_COLUMNC = -1
    PANEL_STYLE_CITY_COLUMNR = -1
    PANEL_STYLE_CITY_TITLE = -1

    PANEL_STYLE_DAWN = -1
    PANEL_STYLE_DAWNTOP = -1
    PANEL_STYLE_DAWNBOTTOM = -1

    PANEL_STYLE_MAIN = -1
    PANEL_STYLE_MAIN_BLACK25 = -1
    PANEL_STYLE_MAIN_BLACK50 = -1
    PANEL_STYLE_MAIN_WHITE = -1
    PANEL_STYLE_MAIN_WHITETAB = -1
    PANEL_STYLE_MAIN_TAN = -1
    PANEL_STYLE_MAIN_TAN15 = -1
    PANEL_STYLE_MAIN_TANL = -1
    PANEL_STYLE_MAIN_TANR = -1
    PANEL_STYLE_MAIN_TANT = -1
    PANEL_STYLE_MAIN_TANB = -1
    PANEL_STYLE_MAIN_BOTTOMBAR = -1
    PANEL_STYLE_MAIN_SELECT = -1

class ButtonStyles(Enum):
    BUTTON_STYLE_STANDARD = -1
    BUTTON_STYLE_ETCHED = -1
    BUTTON_STYLE_FLAT = -1
    BUTTON_STYLE_IMAGE = -1
    BUTTON_STYLE_LABEL = -1
    BUTTON_STYLE_LINK = -1
    BUTTON_STYLE_SQUARE = -1
    BUTTON_STYLE_TOOL = -1
    BUTTON_STYLE_DEFAULT = -1

    BUTTON_STYLE_CIRCLE = -1
    BUTTON_STYLE_CITY_B01 = -1
    BUTTON_STYLE_CITY_B02TL = -1
    BUTTON_STYLE_CITY_B02TR = -1
    BUTTON_STYLE_CITY_B02BL = -1
    BUTTON_STYLE_CITY_B02BR = -1
    BUTTON_STYLE_CITY_B03TL = -1
    BUTTON_STYLE_CITY_B03TC = -1
    BUTTON_STYLE_CITY_B03TR = -1
    BUTTON_STYLE_CITY_B03BL = -1
    BUTTON_STYLE_CITY_B03BC = -1
    BUTTON_STYLE_CITY_B03BR = -1
    BUTTON_STYLE_CITY_FLAT = -1
    BUTTON_STYLE_CITY_PLUS = -1
    BUTTON_STYLE_CITY_MINUS = -1
    BUTTON_STYLE_ARROW_LEFT = -1
    BUTTON_STYLE_ARROW_RIGHT = -1

class TableStyles(Enum):
    TABLE_STYLE_STANDARD = -1
    TABLE_STYLE_EMPTY = -1
    TABLE_STYLE_ALTEMPTY = -1
    TABLE_STYLE_CITY = -1
    TABLE_STYLE_EMPTYSELECTINACTIVE = -1
    TABLE_STYLE_ALTDEFAULT = -1
    TABLE_STYLE_STAGINGROOM = -1

class EventContextTypes(Enum):
    NO_EVENTCONTEXT = -1
    EVENTCONTEXT_SELF = -1
    EVENTCONTEXT_ALL = -1

class TabGroupTypes(Enum):
    NO_TABGROUP = -1

    TABGROUP_GAME = -1
    TABGROUP_INPUT = -1
    TABGROUP_GRAPHICS = -1
    TABGROUP_AUDIO = -1
    TABGROUP_CLOCK = -1

    NUM_TABGROUPS = -1

class ReplayMessageTypes(Enum):
    NO_REPLAY_MESSAGE = -1

    REPLAY_MESSAGE_MAJOR_EVENT = -1
    REPLAY_MESSAGE_CITY_FOUNDED = -1
    REPLAY_MESSAGE_PLOT_OWNER_CHANGE = -1

    NUM_REPLAY_MESSAGE_TYPES = -1

class AudioTag(Enum):
    AUDIOTAG_NONE = -1
    AUDIOTAG_SOUNDID = -1
    AUDIOTAG_CONTEXTID = -1
    AUDIOTAG_SOUNDTYPE = -1
    AUDIOTAG_2DSCRIPT = -1
    AUDIOTAG_3DSCRIPT = -1
    AUDIOTAG_SOUNDSCAPE = -1
    AUDIOTAG_POSITION = -1
    AUDIOTAG_SCRIPTTYPE = -1
    AUDIOTAG_LOADTYPE = -1
    AUDIOTAG_COUNT = -1

class CivilopediaPageTypes(Enum):
    NO_CIVILOPEDIA_PAGE = -1

    CIVILOPEDIA_PAGE_TECH = -1
    CIVILOPEDIA_PAGE_UNIT = -1
    CIVILOPEDIA_PAGE_BUILDING = -1
    CIVILOPEDIA_PAGE_WONDER = -1
    CIVILOPEDIA_PAGE_BONUS = -1
    CIVILOPEDIA_PAGE_IMPROVEMENT = -1
    CIVILOPEDIA_PAGE_PROMOTION = -1
    CIVILOPEDIA_PAGE_UNIT_GROUP = -1
    CIVILOPEDIA_PAGE_CIV = -1
    CIVILOPEDIA_PAGE_LEADER = -1
    CIVILOPEDIA_PAGE_RELIGION = -1
    CIVILOPEDIA_PAGE_CORPORATION = -1
    CIVILOPEDIA_PAGE_CIVIC = -1
    CIVILOPEDIA_PAGE_PROJECT = -1
    CIVILOPEDIA_PAGE_CONCEPT = -1
    CIVILOPEDIA_PAGE_CONCEPT_NEW = -1
    CIVILOPEDIA_PAGE_SPECIALIST = -1
    CIVILOPEDIA_PAGE_TERRAIN = -1
    CIVILOPEDIA_PAGE_FEATURE = -1
    CIVILOPEDIA_PAGE_HINTS = -1
    CIVILOPEDIA_PAGE_MAIN = -1

    NUM_CIVILOPEDIA_PAGE_TYPES = -1

class ActionSubTypes(Enum):
    NO_ACTIONSUBTYPE = -1

    ACTIONSUBTYPE_INTERFACEMODE = -1
    ACTIONSUBTYPE_COMMAND = -1
    ACTIONSUBTYPE_BUILD = -1
    ACTIONSUBTYPE_PROMOTION = -1
    ACTIONSUBTYPE_UNIT = -1
    ACTIONSUBTYPE_RELIGION = -1
    ACTIONSUBTYPE_SPECIALIST = -1
    ACTIONSUBTYPE_BUILDING = -1
    ACTIONSUBTYPE_CONTROL = -1
    ACTIONSUBTYPE_AUTOMATE = -1
    ACTIONSUBTYPE_MISSION = -1

    NUM_ACTIONSUBTYPES = -1

class GameMessageTypes(Enum):
    GAMEMESSAGE_NETWORK_READY = -1
    GAMEMESSAGE_SAVE_GAME_FLAG = -1
    GAMEMESSAGE_SAVE_FLAG_ACK = -1
    GAMEMESSAGE_VERIFY_VERSION = -1
    GAMEMESSAGE_VERSION_NACK = -1
    GAMEMESSAGE_VERSION_WARNING = -1
    GAMEMESSAGE_GAME_TYPE = -1
    GAMEMESSAGE_ID_ASSIGNMENT = -1
    GAMEMESSAGE_FILE_INFO = -1
    GAMEMESSAGE_PICK_YOUR_CIV = -1
    GAMEMESSAGE_CIV_CHOICE = -1
    GAMEMESSAGE_CONFIRM_CIV_CLAIM = -1
    GAMEMESSAGE_CLAIM_INFO = -1
    GAMEMESSAGE_CIV_CHOICE_ACK = -1
    GAMEMESSAGE_CIV_CHOICE_NACK = -1
    GAMEMESSAGE_CIV_CHOSEN = -1
    GAMEMESSAGE_INTERIM_NOTICE = -1
    GAMEMESSAGE_INIT_INFO = -1
    GAMEMESSAGE_MAPSCRIPT_CHECK = -1
    GAMEMESSAGE_MAPSCRIPT_ACK = -1
    GAMEMESSAGE_LOAD_GAME = -1
    GAMEMESSAGE_PLAYER_ID = -1
    GAMEMESSAGE_SLOT_REASSIGNMENT = -1
    GAMEMESSAGE_PLAYER_INFO = -1
    GAMEMESSAGE_GAME_INFO = -1
    GAMEMESSAGE_REASSIGN_PLAYER = -1
    GAMEMESSAGE_PITBOSS_INFO = -1
    GAMEMESSAGE_LAUNCHING_INFO = -1
    GAMEMESSAGE_INIT_GAME = -1
    GAMEMESSAGE_INIT_PLAYERS = -1
    GAMEMESSAGE_AUTH_REQUEST = -1
    GAMEMESSAGE_AUTH_RESPONSE = -1
    GAMEMESSAGE_SYNCH_START = -1
    GAMEMESSAGE_PLAYER_OPTION = -1
    GAMEMESSAGE_EXTENDED_GAME = -1
    GAMEMESSAGE_AUTO_MOVES = -1
    GAMEMESSAGE_TURN_COMPLETE = -1
    GAMEMESSAGE_JOIN_GROUP = -1
    GAMEMESSAGE_PUSH_MISSION = -1
    GAMEMESSAGE_AUTO_MISSION = -1
    GAMEMESSAGE_DO_COMMAND = -1
    GAMEMESSAGE_PUSH_ORDER = -1
    GAMEMESSAGE_POP_ORDER = -1
    GAMEMESSAGE_DO_TASK = -1
    GAMEMESSAGE_RESEARCH = -1
    GAMEMESSAGE_PERCENT_CHANGE = -1
    GAMEMESSAGE_ESPIONAGE_CHANGE = -1
    GAMEMESSAGE_CONVERT = -1
    GAMEMESSAGE_CHAT = -1
    GAMEMESSAGE_PING = -1
    GAMEMESSAGE_SIGN = -1
    GAMEMESSAGE_LINE_ENTITY = -1
    GAMEMESSAGE_SIGN_DELETE = -1
    GAMEMESSAGE_LINE_ENTITY_DELETE = -1
    GAMEMESSAGE_LINE_GROUP_DELETE = -1
    GAMEMESSAGE_PAUSE = -1
    GAMEMESSAGE_MP_KICK = -1
    GAMEMESSAGE_MP_RETIRE = -1
    GAMEMESSAGE_CLOSE_CONNECTION = -1
    GAMEMESSAGE_NEVER_JOINED = -1
    GAMEMESSAGE_MP_DROP_INIT = -1
    GAMEMESSAGE_MP_DROP_VOTE = -1
    GAMEMESSAGE_MP_DROP_UPDATE = -1
    GAMEMESSAGE_MP_DROP_RESULT = -1
    GAMEMESSAGE_MP_DROP_SAVE = -1
    GAMEMESSAGE_TOGGLE_TRADE = -1
    GAMEMESSAGE_IMPLEMENT_OFFER = -1
    GAMEMESSAGE_CHANGE_WAR = -1
    GAMEMESSAGE_CHANGE_VASSAL = -1
    GAMEMESSAGE_CHOOSE_ELECTION = -1
    GAMEMESSAGE_DIPLO_VOTE = -1
    GAMEMESSAGE_APPLY_EVENT = -1
    GAMEMESSAGE_CONTACT_CIV = -1
    GAMEMESSAGE_DIPLO_CHAT = -1
    GAMEMESSAGE_SEND_OFFER = -1
    GAMEMESSAGE_DIPLO_EVENT = -1
    GAMEMESSAGE_RENEGOTIATE = -1
    GAMEMESSAGE_RENEGOTIATE_ITEM = -1
    GAMEMESSAGE_EXIT_TRADE = -1
    GAMEMESSAGE_KILL_DEAL = -1
    GAMEMESSAGE_SAVE_GAME = -1
    GAMEMESSAGE_UPDATE_CIVICS = -1
    GAMEMESSAGE_CLEAR_TABLE = -1
    GAMEMESSAGE_POPUP_PROCESSED = -1
    GAMEMESSAGE_DIPLOMACY_PROCESSED = -1
    GAMEMESSAGE_HOT_JOIN_NOTICE = -1
    GAMEMESSAGE_HOT_DROP_NOTICE = -1
    GAMEMESSAGE_DIPLOMACY = -1
    GAMEMESSAGE_POPUP = -1
    GAMEMESSAGE_EVENT_TRIGGERED = -1
    GAMEMESSAGE_EMPIRE_SPLIT = -1
    GAMEMESSAGE_LAUNCH_SPACESHIP = -1
    GAMEMESSAGE_ADVANCED_START_ACTION = -1
    GAMEMESSAGE_FOUND_RELIGION = -1
    GAMEMESSAGE_MOD_NET_MESSAGE = -1

class PopupControlLayout(Enum):
    POPUP_LAYOUT_LEFT = -1
    POPUP_LAYOUT_CENTER = -1
    POPUP_LAYOUT_RIGHT = -1
    POPUP_LAYOUT_STRETCH = -1
    POPUP_LAYOUT_NUMLAYOUTS = -1

class JustificationTypes(Enum):
    DLL_FONT_LEFT_JUSTIFY = -1
    DLL_FONT_RIGHT_JUSTIFY = -1
    DLL_FONT_CENTER_JUSTIFY = -1
    DLL_FONT_CENTER_VERTICALLY = -1
    DLL_FONT_ADDITIVE = -1

class ToolTipAlignTypes(Enum):
    TOOLTIP_TOP_LEFT = -1
    TOOLTIP_TOP_INLEFT = -1
    TOOLTIP_TOP_CENTER = -1
    TOOLTIP_TOP_INRIGHT = -1
    TOOLTIP_TOP_RIGHT = -1

    TOOLTIP_INTOP_RIGHT = -1
    TOOLTIP_CENTER_RIGHT = -1
    TOOLTIP_INBOTTOM_RIGHT = -1

    TOOLTIP_BOTTOM_RIGHT = -1
    TOOLTIP_BOTTOM_INRIGHT = -1
    TOOLTIP_BOTTOM_CENTER = -1
    TOOLTIP_BOTTOM_INLEFT = -1
    TOOLTIP_BOTTOM_LEFT = -1

    TOOLTIP_INBOTTOM_LEFT = -1
    TOOLTIP_CENTER_LEFT = -1
    TOOLTIP_INTOP_LEFT = -1

class ActivationTypes(Enum):
    ACTIVATE_NORMAL = -1
    ACTIVATE_CHILDFOCUS = -1
    ACTIVATE_MIMICPARENT = -1
    ACTIVATE_MIMICPARENTFOCUS = -1

class HitTestTypes(Enum):
    HITTEST_DEFAULT = -1
    HITTEST_NOHIT = -1
    HITTEST_SOLID = -1
    HITTEST_ON = -1
    HITTEST_CHILDREN = -1

class GraphicLevelTypes(Enum):
    GRAPHICLEVEL_HIGH = -1
    GRAPHICLEVEL_MEDIUM = -1
    GRAPHICLEVEL_LOW = -1
    GRAPHICLEVEL_CURRENT = -1
    NUM_GRAPHICLEVELS = -1

class EventTypes(Enum):
    NO_EVENT = -1

class EventTriggerTypes(Enum):
    NO_EVENTTRIGGER = -1

class EspionageMissionTypes(Enum):
    NO_ESPIONAGEMISSION = -1

class AdvancedStartActionTypes(Enum):
    NO_ADVANCEDSTARTACTION = -1

    ADVANCEDSTARTACTION_EXIT = -1
    ADVANCEDSTARTACTION_UNIT = -1
    ADVANCEDSTARTACTION_CITY = -1
    ADVANCEDSTARTACTION_POP = -1
    ADVANCEDSTARTACTION_CULTURE = -1
    ADVANCEDSTARTACTION_BUILDING = -1
    ADVANCEDSTARTACTION_IMPROVEMENT = -1
    ADVANCEDSTARTACTION_ROUTE = -1
    ADVANCEDSTARTACTION_TECH = -1
    ADVANCEDSTARTACTION_VISIBILITY = -1
    ADVANCEDSTARTACTION_AUTOMATE = -1

class InputTypes(Enum):
    KB_NONE = -1  # 0
    KB_ESCAPE = -1
    KB_0 = -1
    KB_1 = -1
    KB_2 = -1
    KB_3 = -1
    KB_4 = -1
    KB_5 = -1
    KB_6 = -1
    KB_7 = -1
    KB_8 = -1
    KB_9 = -1
    KB_MINUS = -1
    KB_A = -1
    KB_B = -1
    KB_C = -1
    KB_D = -1
    KB_E = -1
    KB_F = -1
    KB_G = -1
    KB_H = -1
    KB_I = -1
    KB_J = -1
    KB_K = -1
    KB_L = -1
    KB_M = -1
    KB_N = -1
    KB_O = -1
    KB_P = -1
    KB_Q = -1
    KB_R = -1
    KB_S = -1
    KB_T = -1
    KB_U = -1
    KB_V = -1
    KB_W = -1
    KB_X = -1
    KB_Y = -1
    KB_Z = -1
    KB_EQUALS = -1
    KB_BACKSPACE = -1
    KB_TAB = -1
    KB_LBRACKET = -1
    KB_RBRACKET = -1
    KB_RETURN = -1
    KB_LCONTROL = -1
    KB_SEMICOLON = -1
    KB_APOSTROPHE = -1
    KB_GRAVE = -1
    KB_LSHIFT = -1
    KB_BACKSLASH = -1
    KB_COMMA = -1
    KB_PERIOD = -1
    KB_SLASH = -1
    KB_RSHIFT = -1
    KB_NUMPADSTAR = -1
    KB_LALT = -1
    KB_SPACE = -1
    KB_CAPSLOCK = -1
    KB_F1 = -1
    KB_F2 = -1
    KB_F3 = -1
    KB_F4 = -1
    KB_F5 = -1
    KB_F6 = -1
    KB_F7 = -1
    KB_F8 = -1
    KB_F9 = -1
    KB_F10 = -1
    KB_F11 = -1
    KB_F12 = -1
    KB_NUMLOCK = -1
    KB_SCROLL = -1
    KB_NUMPAD0 = -1
    KB_NUMPAD1 = -1
    KB_NUMPAD2 = -1
    KB_NUMPAD3 = -1
    KB_NUMPAD4 = -1
    KB_NUMPAD5 = -1
    KB_NUMPAD6 = -1
    KB_NUMPAD7 = -1
    KB_NUMPAD8 = -1
    KB_NUMPAD9 = -1
    KB_NUMPADMINUS = -1
    KB_NUMPADPLUS = -1
    KB_NUMPADPERIOD = -1
    KB_NUMPADEQUALS = -1
    KB_AT = -1
    KB_UNDERLINE = -1
    KB_COLON = -1
    KB_NUMPADENTER = -1
    KB_RCONTROL = -1
    KB_VOLUMEDOWN = -1
    KB_VOLUMEUP = -1
    KB_NUMPADCOMMA = -1
    KB_NUMPADSLASH = -1
    KB_SYSRQ = -1
    KB_RALT = -1
    KB_PAUSE = -1
    KB_HOME = -1
    KB_UP = -1
    KB_PGUP = -1
    KB_LEFT = -1
    KB_RIGHT = -1
    KB_END = -1
    KB_DOWN = -1
    KB_PGDN = -1
    KB_INSERT = -1
    KB_DELETE = -1

    M_NONE = -1
    M_LEFT = -1
    M_CENTER = -1
    M_RIGHT = -1
    M_FORWARD = -1
    M_BACKWARD = -1
    M_WHEEL = -1

    NUM_INPUT_TYPE = -1
    NONE = 0

class NotifyCode(Enum):
    NOTIFY_CHARACTER = -1
    NOTIFY_CLICKED = -1
    NOTIFY_CURSOR_MOVE_OFF = -1
    NOTIFY_CURSOR_MOVE_ON = -1
    NOTIFY_LISTBOX_ITEM_SELECTED = -1
    NOTIFY_MOVIE_DONE = -1
    NOTIFY_SLIDER_NEWSTOP = -1

class MouseFlags(Enum):
    MOUSE_LBUTTONUP = -1
    MOUSE_RBUTTONUP = -1
