
""" Lists of TXT_KEY's. This lists will be checked to write
		the keys instead of raw names into the Worldbuilder saves.
		The list requires a manual update if some szenario will be changed.
"""

# Desc and ShortDesc
CivDescKeys = [
        ]

# CivAdjective
CivAdjectiveKeys = [
        ]

# LeaderName
LeaderKeys = [
        ]

UnitNameKeys = [ ]  # Not used
 
CityKeys = [
        ]

# Load autogenerated values and unload module after its usage.
try:
    import sys
    import CvWBKeys_auto
    CivDescKeys.extend(CvWBKeys_auto.CivDescKeys)
    CivAdjectiveKeys.extend(CvWBKeys_auto.CivAdjectiveKeys)
    LeaderKeys.extend(CvWBKeys_auto.LeaderKeys)
    CityKeys.extend(CvWBKeys_auto.CityKeys)

    del sys.modules['CvWBKeys_auto']  # Module not needed anymore
except Exception as e:
    raise(e)
    pass


# Some city keys are used as Civ/Leader keys, too.
# => Add the cities keys to the other arrays 
LeaderKeys.extend(CityKeys)
CivDescKeys.extend(CityKeys)
CivAdjectiveKeys.extend(CityKeys)

print(LeaderKeys)
