# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 22:09
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbspy', '0007_auto_20171121_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='victory_image',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.URLValidator(regex='^.*[.](png|jpg|jpeg|git|php[?].*)$')]),
        ),
    ]
