# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-22 00:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('pbspy', '0008_auto_20171121_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelogmissedturn',
            name='missed_turn_ids',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
