# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-05 08:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('pbspy', '0010_auto_20181012_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='victory_image',
            field=models.CharField(blank=True, max_length=200, null=True, validators=[django.core.validators.URLValidator(regex='^.*[.](png|jpg|jpeg|gif|php[?].*)$')]),
        ),
        migrations.AlterField(
            model_name='gamelogmissedturn',
            name='missed_turn_ids',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
