# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-01-08 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pbspy', '0011_auto_20190105_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='last_update_attempt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
