# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 17:17
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('pbspy', '0012_auto_20190108_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelogmissedturn',
            name='missed_turn_ids',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:,\\d+)*\\Z', 32), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
