# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-02 17:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pbspy', '0013_auto_20190402_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamelogcurrenttimerchanged',
            name='from_4s',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogcurrenttimerchanged',
            name='to_4s',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gamelogtimerchanged',
            name='timer_max_h',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
