# Generated by Django 2.2.9 on 2020-01-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pbspy', '0014_auto_20190402_1719'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamelog',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogadminaction',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogadminendturn',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogadminpause',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogadminsave',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogai',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogclaimed',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogcurrenttimerchanged',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogeliminated',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogfinish',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogforcedisconnect',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gameloglogin',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gameloglogout',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogmetachange',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogmissedturn',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelognamechange',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogpause',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogplayer',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogreload',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogscore',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogservertimeout',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogtimerchanged',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelOptions(
            name='gamelogturn',
            options={'base_manager_name': 'objects'},
        ),
    ]
