# Generated by Django 2.2 on 2020-06-26 09:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pbspy', '0015_auto_20200126_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='subscribed_users',
            field=models.ManyToManyField(blank=True, related_name='subscribed_players', to=settings.AUTH_USER_MODEL),
        ),
    ]
